import argparse
import os
import sys
import re
from datetime import datetime, timezone
from dataclasses import dataclass, replace
from pathlib import Path

import orjson


ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "05_src"

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from decathlon_voc_analyzer.runtime_progress import WorkflowProgressReporter, use_workflow_progress


REVIEW_FLAG_PATTERN = re.compile(r"^--R_(\d+)$")


@dataclass(frozen=True)
class WorkflowCliConfig:
    dataset_root: Path
    output_base: Path
    prompt_variant: str
    mode_label: str
    retrieval_backend: str
    qdrant_path: Path


@dataclass(frozen=True)
class WorkflowExecutionSummary:
    mode_label: str
    dataset_root: str
    prompt_variant: str
    reports_output_dir: str
    category: str
    product_id: str
    max_reviews: int | None
    overview: dict[str, int]
    normalization: dict[str, object] | None
    index_result: dict[str, object] | None
    review_sampling: dict[str, object] | None
    retrieval_runtime: dict[str, object] | None
    analysis: dict[str, object]
    artifact_bundle: dict[str, str | None] | None
    html_export_path: str | None
    manifest_path: str | None


WORKFLOW_PROGRESS_PLAN = [
    ("overview", "Dataset Overview", [("scan", "Scan Categories & Products"), ("summarize", "Summarize Overview")]),
    ("normalize", "Normalize Data", [("select", "Select Target Products"), ("normalize_products", "Normalize Products"), ("persist", "Persist Normalization")]),
    ("index", "Build Index", [("load_packages", "Load Product Packages"), ("embed_text", "Generate Text Embeddings"), ("embed_image", "Generate Image Embeddings"), ("persist", "Save Index Snapshot")]),
    ("analyze", "Generate Analysis", [("extract", "Extract Reviews"), ("questions", "Plan & Generate Questions"), ("retrieve", "Retrieve Evidence"), ("quality", "Evaluate Retrieval Quality"), ("report", "Generate Report"), ("attribution", "Attribution & Revision"), ("persist", "Persist Analysis Artifacts")]),
    ("export_html", "Export HTML", [("render", "Render HTML"), ("write", "Write HTML File")]),
    ("write_manifest", "Write Manifest", [("serialize", "Serialize Summary"), ("write", "Write Manifest File")]),
]


def _preprocess_argv(argv: list[str]) -> list[str]:
    normalized: list[str] = []
    for arg in argv:
        match = REVIEW_FLAG_PATTERN.match(arg)
        if match:
            normalized.extend(["--max-reviews", match.group(1)])
            continue
        normalized.append(arg)
    return normalized


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Decathlon VOC Analyzer workflow")
    parser.add_argument("--cn", action="store_true", help="Chinese mode shorthand: sets Chinese dataset_root, prompt_variant and CN output namespace")
    parser.add_argument("--category", default="backpack", help="Category, e.g. backpack")
    parser.add_argument("--product-id", default="backpack_010", help="Product ID, e.g. backpack_010")
    parser.add_argument("--dataset-root", default=None, help="Optional: explicit dataset root, e.g. 01_data/02_audit_zh_products/products")
    parser.add_argument("--prompt-variant", default=None, help="Optional: prompt variant, e.g. main, cn, zh-cn")
    parser.add_argument("--output-namespace", default=None, help="Optional: output namespace dir, e.g. CN; empty writes to default 02_outputs root")
    parser.add_argument("--retrieval-backend", choices=["qdrant", "local"], default="qdrant", help="Default uses qdrant; specify local to fall back")
    parser.add_argument("--qdrant-path", default=None, help="Optional: explicit Qdrant storage dir; auto-generated by qdrant-scope if not set")
    parser.add_argument(
        "--qdrant-scope",
        choices=["isolated", "shared"],
        default="isolated",
        help="Qdrant directory scope; isolated creates per-run dir, shared reuses fixed qdrant_store",
    )
    parser.add_argument("--max-reviews", type=int, default=None, help="Limit number of reviews for analysis")
    parser.add_argument("--top-k-per-route", type=int, default=2, help="Number of evidence items per modality route")
    parser.add_argument("--questions-per-aspect", type=int, default=2, help="Number of questions per aspect")
    parser.add_argument("--no-llm", action="store_true", help="Disable LLM, use local heuristic chain")
    parser.add_argument("--skip-normalize", action="store_true", help="Skip normalization stage")
    parser.add_argument("--skip-index", action="store_true", help="Skip index building stage")
    parser.add_argument("--resume-from-aspects", action="store_true", help="Reuse existing review extraction, continue from questions/retrieve/report")
    parser.add_argument("--resume-from-analysis-checkpoint", action="store_true", help="Reuse existing question & retrieval checkpoint, continue from retrieval_quality/report")
    parser.add_argument("--export-html", action="store_true", help="Export single product HTML page after analysis")
    parser.add_argument("--write-manifest", action="store_true", help="Write run summary as manifest JSON")
    parser.add_argument("--manifest-path", default=None, help="Optional: explicit manifest output path")
    parser.add_argument("--output-format", choices=["text", "json"], default="text", help="Output format; json recommended for batch processing")
    parser.add_argument("--quiet", action="store_true", help="Quiet mode; only print final summary in text output")
    parser.epilog = "Supports shorthand flags, e.g.: --R_5 means analyze only first 5 reviews"
    return parser.parse_args(_preprocess_argv(sys.argv[1:]))


def _resolve_dataset_root(args: argparse.Namespace) -> Path:
    if args.dataset_root:
        candidate = Path(args.dataset_root)
        return candidate if candidate.is_absolute() else (ROOT_DIR / candidate)
    if args.cn:
        return ROOT_DIR / "01_data" / "02_audit_zh_products" / "products"
    return ROOT_DIR / "01_data" / "01_raw_products" / "products"


def _resolve_output_base(args: argparse.Namespace) -> Path:
    namespace = args.output_namespace
    if namespace is None and args.cn:
        namespace = "CN"
    return ROOT_DIR / "02_outputs" / namespace if namespace else ROOT_DIR / "02_outputs"


def _resolve_prompt_variant(args: argparse.Namespace) -> str:
    from decathlon_voc_analyzer.prompts import normalize_prompt_variant

    if args.prompt_variant:
        return normalize_prompt_variant(args.prompt_variant)
    return normalize_prompt_variant("CN" if args.cn else "main")


def _mode_label_for_variant(prompt_variant: str) -> str:
    return "Chinese Dataset" if prompt_variant == "CN" else "Main Project Dataset"


def _thread_scope_label(args: argparse.Namespace, prompt_variant: str) -> str:
    return "cn" if prompt_variant == "CN" else "default"


def _build_run_stamp() -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S_%fZ")
    return f"run_{timestamp}_pid{os.getpid()}"


def _resolve_qdrant_path(args: argparse.Namespace, output_base: Path) -> Path:
    if args.qdrant_path:
        candidate = Path(args.qdrant_path)
        return candidate if candidate.is_absolute() else (ROOT_DIR / candidate)
    shared_path = output_base / "3_indexes" / "qdrant_store"
    if args.qdrant_scope == "shared":
        return shared_path
    return output_base / "3_indexes" / "qdrant_runs" / args.category / args.product_id / _build_run_stamp()


def build_cli_config(args: argparse.Namespace) -> WorkflowCliConfig:
    dataset_root = _resolve_dataset_root(args)
    output_base = _resolve_output_base(args)
    prompt_variant = _resolve_prompt_variant(args)
    mode_label = _mode_label_for_variant(prompt_variant)
    qdrant_path = _resolve_qdrant_path(args, output_base)
    return WorkflowCliConfig(
        dataset_root=dataset_root,
        output_base=output_base,
        prompt_variant=prompt_variant,
        mode_label=mode_label,
        retrieval_backend=args.retrieval_backend,
        qdrant_path=qdrant_path,
    )


def configure_environment(config: WorkflowCliConfig) -> dict[str, Path]:
    paths = {
        "dataset_root": config.dataset_root,
        "normalized_output_dir": config.output_base / "1_normalized",
        "reports_output_dir": config.output_base / "4_reports",
        "aspects_output_dir": config.output_base / "2_aspects",
        "indexes_output_dir": config.output_base / "3_indexes",
        "feedback_output_dir": config.output_base / "5_feedback",
        "replay_output_dir": config.output_base / "5_replay",
        "html_output_dir": config.output_base / "6_html",
        "manifests_output_dir": config.output_base / "7_manifests",
        "qdrant_path": config.qdrant_path,
    }

    os.environ["PROMPT_VARIANT"] = config.prompt_variant

    os.environ["DATASET_ROOT"] = str(paths["dataset_root"])
    os.environ["NORMALIZED_OUTPUT_DIR"] = str(paths["normalized_output_dir"])
    os.environ["REPORTS_OUTPUT_DIR"] = str(paths["reports_output_dir"])
    os.environ["ASPECTS_OUTPUT_DIR"] = str(paths["aspects_output_dir"])
    os.environ["INDEXES_OUTPUT_DIR"] = str(paths["indexes_output_dir"])
    os.environ["FEEDBACK_OUTPUT_DIR"] = str(paths["feedback_output_dir"])
    os.environ["REPLAY_OUTPUT_DIR"] = str(paths["replay_output_dir"])
    os.environ["HTML_OUTPUT_DIR"] = str(paths["html_output_dir"])
    os.environ["QDRANT_PATH"] = str(paths["qdrant_path"])
    os.environ["RETRIEVAL_BACKEND"] = config.retrieval_backend
    return paths


def _resolve_manifest_path(args: argparse.Namespace, paths: dict[str, Path]) -> Path:
    if args.manifest_path:
        candidate = Path(args.manifest_path)
        return candidate if candidate.is_absolute() else (ROOT_DIR / candidate)
    return paths["manifests_output_dir"] / args.category / f"{args.product_id}_run_manifest.json"


def _resolve_progress_dashboard_path(args: argparse.Namespace, paths: dict[str, Path]) -> Path:
    return paths["html_output_dir"] / "_progress" / args.category / f"{args.product_id}_live_progress.html"


def execute_workflow(args: argparse.Namespace, paths: dict[str, Path], progress: WorkflowProgressReporter | None = None) -> WorkflowExecutionSummary:
    from decathlon_voc_analyzer.app.core.config import get_settings
    from decathlon_voc_analyzer.app.core.runtime_policy import validate_full_power_prerequisites

    get_settings.cache_clear()
    settings = get_settings()
    validate_full_power_prerequisites(
        use_llm=not args.no_llm,
        retrieval_backend=str(os.environ.get("RETRIEVAL_BACKEND") or settings.retrieval_backend),
        settings=settings,
    )

    from decathlon_voc_analyzer.stage4_generation.html_export_service import HtmlExportService
    from decathlon_voc_analyzer.workflows.single_product_workflow import get_single_product_workflow

    workflow = get_single_product_workflow()
    if progress is not None:
        progress.note("Workflow started, executing modules in sequence.")
    result = workflow.invoke(
        {
            "category": args.category,
            "product_id": args.product_id,
            "max_reviews": args.max_reviews,
            "top_k_per_route": args.top_k_per_route,
            "questions_per_aspect": args.questions_per_aspect,
            "use_llm": not args.no_llm,
            "skip_normalize": args.skip_normalize,
            "skip_index": args.skip_index,
            "reuse_extraction_artifact": args.resume_from_aspects,
            "reuse_analysis_checkpoint": args.resume_from_analysis_checkpoint,
        },
        config={"configurable": {"thread_id": f"workflow:{_thread_scope_label(args, str(os.environ.get('PROMPT_VARIANT') or 'main'))}:{args.category}:{args.product_id}"}},
    )

    overview = result["overview"]
    normalization = result.get("normalization")
    index_result = result.get("index_result")
    analysis = result["analysis"]
    sampling_plan = analysis.extraction.sampling_plan
    retrieval_runtime = analysis.retrieval_runtime.model_dump(mode="json") if analysis.retrieval_runtime is not None else None
    html_export_path = None
    if args.export_html:
        if progress is not None:
            progress.activate_module("export_html", detail="Preparing to export single product HTML page")
            progress.activate_step("export_html", "render", detail="Reading analysis results and generating HTML content")
        analysis_path = Path(str(analysis.artifact_path)) if analysis.artifact_path else None
        normalized_path = paths["normalized_output_dir"] / args.category / f"{args.product_id}.json"
        if analysis_path is not None and analysis_path.exists():
            analysis_payload = orjson.loads(analysis_path.read_bytes())
            normalized_payload = orjson.loads(normalized_path.read_bytes()) if normalized_path.exists() else None
            html_content = HtmlExportService().render(analysis_payload=analysis_payload, normalized_payload=normalized_payload)
            html_target_dir = paths["html_output_dir"] / args.category
            html_target_dir.mkdir(parents=True, exist_ok=True)
            html_output_path = html_target_dir / f"{args.product_id}.html"
            html_output_path.write_text(html_content, encoding="utf-8")
            html_export_path = str(html_output_path)
        if progress is not None:
            progress.complete_step("export_html", "render")
            progress.activate_step("export_html", "write", detail=f"{html_export_path or 'no output written'}")
            progress.complete_step("export_html", "write")
            progress.complete_module("export_html")

    return WorkflowExecutionSummary(
        mode_label=_mode_label_for_variant(str(os.environ.get("PROMPT_VARIANT") or "main")),
        dataset_root=str(paths["dataset_root"]),
        prompt_variant=str(os.environ.get("PROMPT_VARIANT") or "main"),
        reports_output_dir=str(paths["reports_output_dir"]),
        category=args.category,
        product_id=args.product_id,
        max_reviews=args.max_reviews,
        overview={
            "category_count": overview.category_count,
            "total_products": overview.total_products,
            "total_reviews": overview.total_reviews,
        },
        normalization=(
            {
                "normalized_products": normalization.stats.normalized_products,
                "report_path": normalization.report_path,
            }
            if normalization is not None
            else None
        ),
        index_result=(
            {
                "backend": index_result.backend,
                "indexed_products": index_result.stats.indexed_products,
                "index_path": index_result.index_path,
            }
            if index_result is not None
            else None
        ),
        review_sampling=(sampling_plan.model_dump(mode="json") if sampling_plan is not None else None),
        retrieval_runtime=retrieval_runtime,
        analysis={
            "analysis_mode": analysis.analysis_mode,
            "artifact_path": analysis.artifact_path,
            "strengths": len(analysis.report.strengths),
            "weaknesses": len(analysis.report.weaknesses),
            "replay_applied": bool(analysis.replay_summary and analysis.replay_summary.applied),
            "replay_persistent_issue_count": len(analysis.replay_summary.persistent_issue_labels) if analysis.replay_summary else 0,
            "replay_resolved_issue_count": len(analysis.replay_summary.resolved_issue_labels) if analysis.replay_summary else 0,
            "warnings": list(analysis.warnings),
        },
        artifact_bundle=(analysis.artifact_bundle.model_dump(mode="json") if analysis.artifact_bundle is not None else None),
        html_export_path=html_export_path,
        manifest_path=None,
    )


def _summary_payload(summary: WorkflowExecutionSummary) -> dict[str, object]:
    return {
        "mode_label": summary.mode_label,
        "dataset_root": summary.dataset_root,
        "prompt_variant": summary.prompt_variant,
        "reports_output_dir": summary.reports_output_dir,
        "category": summary.category,
        "product_id": summary.product_id,
        "max_reviews": summary.max_reviews,
        "overview": summary.overview,
        "normalization": summary.normalization,
        "index_result": summary.index_result,
        "review_sampling": summary.review_sampling,
        "retrieval_runtime": summary.retrieval_runtime,
        "analysis": summary.analysis,
        "artifact_bundle": summary.artifact_bundle,
        "html_export_path": summary.html_export_path,
        "manifest_path": summary.manifest_path,
    }


def maybe_write_manifest(args: argparse.Namespace, summary: WorkflowExecutionSummary, paths: dict[str, Path], progress: WorkflowProgressReporter | None = None) -> WorkflowExecutionSummary:
    if not args.write_manifest and not args.manifest_path:
        return summary
    manifest_path = _resolve_manifest_path(args, paths)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    if progress is not None:
        progress.activate_module("write_manifest", detail="Preparing to write run summary")
        progress.activate_step("write_manifest", "serialize", detail="Organizing summary JSON")
    materialized_summary = replace(summary, manifest_path=str(manifest_path))
    manifest_path.write_bytes(orjson.dumps(_summary_payload(materialized_summary), option=orjson.OPT_INDENT_2))
    if progress is not None:
        progress.complete_step("write_manifest", "serialize")
        progress.activate_step("write_manifest", "write", detail=str(manifest_path))
        progress.complete_step("write_manifest", "write")
        progress.complete_module("write_manifest")
    return materialized_summary


def _render_text_summary(summary: WorkflowExecutionSummary, quiet: bool) -> str:
    lines: list[str] = []
    if not quiet:
        lines.append(f"[1/4] Current mode: {summary.mode_label}")
        lines.append(f"       dataset_root = {summary.dataset_root}")
        lines.append(f"       prompt_variant = {summary.prompt_variant}")
        lines.append(f"       reports_output_dir = {summary.reports_output_dir}")
        lines.append(
            f"[2/4] Dataset overview: categories={summary.overview['category_count']}, products={summary.overview['total_products']}, reviews={summary.overview['total_reviews']}"
        )
        if summary.max_reviews is not None:
            lines.append(f"       review_limit = {summary.max_reviews}")
        if summary.normalization is not None:
            lines.append(
                "[3/4] Normalization complete: "
                f"normalized_products={summary.normalization['normalized_products']}, "
                f"report_path={summary.normalization['report_path']}"
            )
        else:
            lines.append("[3/4] Normalization skipped")
        if summary.index_result is not None:
            lines.append(
                "[4/4] Index build complete: "
                f"backend={summary.index_result['backend']}, "
                f"indexed_products={summary.index_result['indexed_products']}, "
                f"index_path={summary.index_result['index_path']}"
            )
        else:
            lines.append("[4/4] Index build skipped")

    lines.append("[Done] Analysis generated")
    lines.append(f"       analysis_mode = {summary.analysis['analysis_mode']}")
    lines.append(f"       artifact_path = {summary.analysis['artifact_path']}")
    lines.append(f"       strengths = {summary.analysis['strengths']}")
    lines.append(f"       weaknesses = {summary.analysis['weaknesses']}")
    if summary.retrieval_runtime is not None:
        lines.append(f"       native_multimodal_enabled = {summary.retrieval_runtime.get('native_multimodal_enabled')}")
        lines.append(f"       image_embedding_backend = {summary.retrieval_runtime.get('image_embedding_backend')}")
        lines.append(f"       multimodal_reranker_backend = {summary.retrieval_runtime.get('multimodal_reranker_backend')}")
    if summary.artifact_bundle is not None:
        lines.append(f"       feedback_path = {summary.artifact_bundle.get('feedback_path')}")
        lines.append(f"       replay_path = {summary.artifact_bundle.get('replay_path')}")
    if summary.html_export_path:
        lines.append(f"       html_export_path = {summary.html_export_path}")
    if summary.manifest_path:
        lines.append(f"       manifest_path = {summary.manifest_path}")
    warnings = summary.analysis["warnings"]
    if warnings:
        lines.append("       warnings:")
        for warning in warnings[:10]:
            lines.append(f"       - {warning}")
    return "\n".join(lines)


def _render_json_summary(summary: WorkflowExecutionSummary) -> bytes:
    return orjson.dumps(_summary_payload(summary), option=orjson.OPT_INDENT_2)


def main() -> None:
    from decathlon_voc_analyzer.stage3_retrieval.index_backends import dispose_index_backend
    from decathlon_voc_analyzer.app.core.runtime_policy import RuntimePolicyError

    args = parse_args()
    config = build_cli_config(args)
    paths = configure_environment(config)
    progress_dashboard_path = _resolve_progress_dashboard_path(args, paths)
    
    # Clear old progress state for new run so dashboard resets to 'running' instead of showing old 'error' state
    restore_state = args.resume_from_aspects or args.resume_from_analysis_checkpoint
    if not restore_state:
        old_state_path = progress_dashboard_path.with_suffix(".state.json")
        if old_state_path.exists():
            old_state_path.unlink()
    
    progress = WorkflowProgressReporter(
        WORKFLOW_PROGRESS_PLAN,
        enabled=not args.quiet,
        dashboard_path=progress_dashboard_path,
        dashboard_title=f"{args.category}/{args.product_id} Workflow Progress",
        terminal_mode="events",
        restore_state=restore_state,
    )
    try:
        try:
            with progress:
                with use_workflow_progress(progress):
                    try:
                        progress.note(f"Workflow started, executing modules in sequence. Dashboard: {progress_dashboard_path}")
                        summary = execute_workflow(args, paths, progress=progress)
                        summary = maybe_write_manifest(args, summary, paths, progress=progress)
                        if args.output_format == "json":
                            sys.stdout.buffer.write(_render_json_summary(summary))
                            sys.stdout.write("\n")
                            return
                        print(_render_text_summary(summary, quiet=args.quiet))
                    except Exception as exc:
                        progress.fail_workflow(detail=f"Unhandled exception: {exc}")
                        raise
        except KeyboardInterrupt as exc:
            print("[Interrupted] Workflow manually cancelled.", file=sys.stderr)
            raise SystemExit(130) from exc
        except RuntimePolicyError as exc:
            print(exc.render(), file=sys.stderr)
            raise SystemExit(1) from exc
    finally:
        dispose_index_backend()


if __name__ == "__main__":
    main()